### ISSUE TITLE
Youtube breaks on navigation

### ISSUE THREAD

**Issue by jerinphilip** [jelmervdl/firefox-translations#12]
We've discussed this in Slack, opening here so information survives slack limits with an older screenshot. Assuming still not solved.

![image](https://user-images.githubusercontent.com/727292/155509347-a731e786-6819-49ce-ad2e-cb55a2cda740.png)

> It seems Youtube references specific elements from Javascript and when translation comes in and replaces those elements, the references are lost. So elements are not updated when you go to a new video (because really you’re staying on the same page, javascript just tries to replace all the content)

**Comment by jelmervdl** [comment]
Support has improved since v0.2.0 which re-uses existing HTML tags. In d3851b43aa025bcc6fd1e79cc66f944f96eb78d6 I started ignoring `<template>` tags which fixed the comments being translated. As far as I can tell, somewhere along the way the buttons becoming empty has also been fixed.

Still broken:
- Video title (right below the video) is not updated while navigating Youtube
- Video description is not being translated while navigating Youtube

**Comment by jelmervdl** [comment]
Google Chrome using Google Translate also fails to translate Youtube apparently. I'm still not sure what Youtube does but it is probably not very common.
![image](https://user-images.githubusercontent.com/198639/156764985-1fa4c895-4ab7-40fe-82c9-729c20c8ce9e.png)
